name: App Integration Test

on:
  workflow_call:

jobs:
  docker_unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Eliona mock
        run: |
          git clone https://github.com/eliona-smart-building-assistant/eliona-mock.git
          cd eliona-mock
          docker-compose up -d

      - name: Wait for Eliona mock to be up
        run: |
          until nc -z localhost 3000; do sleep 1; done

      - name: Run integration test
        id: run_integration_test
        run: go test -v -run TestApp
        env:
          CONNECTION_STRING: postgres://postgres:secretX@172.17.0.1:5432?sslmode=disable
          API_ENDPOINT: http://172.17.0.1:3000/v2
          API_TOKEN: secret
          START_MODE: docker

      - name: Notify failures
#        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_WEBHOOK: ${{ secrets.APPS_MONITORING_SLACK_WEBHOOK }}
          SLACK_MESSAGE: "${{ job.status }}: Integration test for app ${{ github.repository }}"
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/104902996?s=400&u=c6e69d52661bf0947595ccf02471246fd2090eba
          
