name: App Integration Test

on:
  workflow_call:

jobs:
  docker_unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Eliona mock
        run: |
          git clone https://github.com/eliona-smart-building-assistant/eliona-mock.git
          cd eliona-mock
          docker-compose up -d

      - name: Wait for Eliona mock to be up
        run: |
          until nc -z localhost 3000; do sleep 1; done

      - name: Run integration test
        id: run_integration_test
        run: go test -v -run TestApp >> $GITHUB_OUTPUT
        env:
          CONNECTION_STRING: postgres://postgres:secretX@172.17.0.1:5432?sslmode=disable
          API_ENDPOINT: http://172.17.0.1:3000/v2
          API_TOKEN: secret
          START_MODE: docker

      - name: Notify failures
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Integration Test for ${{ github.repository }}: ${{ job.status }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "[Failed Integration Test](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\n\n{{join(steps.run_integration_test.outputs.*, '\n')}}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.APPS_MONITORING_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
