name: Code Analysis

on:
  workflow_call:

jobs:
  code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run go fmt to see everything is formatted well
        run: |
          output=$(go fmt ./...)

          if [[ -n $output ]]; then
            echo "There are files that need formatting:"
            echo "$output"
            exit 1
          fi

      - name: Run go vet to see code problems
        run: |
          go vet ./...

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_WEBHOOK: ${{ secrets.APPS_MONITORING_SLACK_WEBHOOK }}
          SLACK_MESSAGE: "${{ job.status }}: Code analysis for app ${{ github.repository }}"
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/104902996?s=400&u=c6e69d52661bf0947595ccf02471246fd2090eba
