name: Code Analysis

on:
  workflow_call:

jobs:
  code_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run staticcheck to finde some code problems
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"

      - name: Run go vet to see code problems
        run: |
          go vet ./...